<?php
/**
 * OfferApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Ebay\Sell\Inventory
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.14.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Ebay\Sell\Inventory\Test\Api;

use \Ebay\Sell\Inventory\Configuration;
use \Ebay\Sell\Inventory\ApiException;
use \Ebay\Sell\Inventory\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OfferApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ebay\Sell\Inventory
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for bulkCreateOffer
     *
     * .
     *
     */
    public function testBulkCreateOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for bulkPublishOffer
     *
     * .
     *
     */
    public function testBulkPublishOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for createOffer
     *
     * .
     *
     */
    public function testCreateOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deleteOffer
     *
     * .
     *
     */
    public function testDeleteOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getListingFees
     *
     * .
     *
     */
    public function testGetListingFees()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOffer
     *
     * .
     *
     */
    public function testGetOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getOffers
     *
     * .
     *
     */
    public function testGetOffers()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for publishOffer
     *
     * .
     *
     */
    public function testPublishOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for publishOfferByInventoryItemGroup
     *
     * .
     *
     */
    public function testPublishOfferByInventoryItemGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateOffer
     *
     * .
     *
     */
    public function testUpdateOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for withdrawOffer
     *
     * .
     *
     */
    public function testWithdrawOffer()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for withdrawOfferByInventoryItemGroup
     *
     * .
     *
     */
    public function testWithdrawOfferByInventoryItemGroup()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
